export const apiKey = 'c42f12d228ae45049a2142354240803';

export const weatherImages = {
    'Partly cloudy': require('../assets/partlyCloud.png'),
    'Moderate rain': require('../assets/moderateRain.png'),
    'Patchy rain possible': require('../assets/moderateRain.png'),
    'Moderate rain at times': require('../assets/moderateRain.png'),
    'Light rain': require('../assets/moderateRain.png'),
    'Sunny': require('../assets/sun.png'),
    'Clear': require('../assets/sun.png'),
    'Overcast': require('../assets/cloud.png'),
    'Cloudy': require('../assets/cloud.png'),
    'Heavy rain': require('../assets/heavyRain.png'),
    'Moderate or heavy freezing rain at times': require('../assets/heavyRain.png'),
    'Heavy rain at times': require('../assets/heavyRain.png'),
    'Moderate or heavy rain with thunder': require('../assets/heavyRain.png'),
    'Patchy rain nearby': require('../assets/moderateRain.png'),
    'Patchy light snow with thunder': require('../assets/snowwithThunder.png'),
    'Moderate or heavy snow with thunder': require('../assets/snowwithThunder.png'),
    'Mist': require('../assets/mist.png'),
    'Moderate snow': require('../assets/snow.png'),
    'Thundery outbreaks possible': require('../assets/heavyRain.png'),
    'Patchy freezing drizzle possible': require('../assets/mist.png'),
    'Patchy snow possible': require('../assets/snow.png'),
    'Blizzard': require('../assets/snow.png'),
    'Blowing snow': require('../assets/snow.png'),
    'Heavy snow': require('../assets/snow.png'),
    'Patchy snow possible': require('../assets/snow.png'),
    'Fog': require('../assets/mist.png'),
    'Freezing fog': require('../assets/mist.png'),
    'Patchy light drizzle': require('../assets/moderateRain.png'),
    'Light drizzle': require('../assets/moderateRain.png'),
    'Freezing drizzle': require('../assets/mist.png'),
    'Heavy freezing drizzle': require('../assets/mist.png'),
    'Light freezing rain': require('../assets/moderateRain.png'),
    'Moderate or heavy freezing rain': require('../assets/heavyRain.png'),
    'Light sleet': require('../assets/snow.png'),
    'Moderate or heavy sleet': require('../assets/snow.png'),
    'Patchy light snow': require('../assets/snow.png'),
    'Patchy moderate snow': require('../assets/snow.png'),
    'Patchy heavy snow': require('../assets/snow.png'),
    'Ice pellets': require('../assets/snow.png'),
    'Light rain shower': require('../assets/moderateRain.png'),
    'Moderate or heavy rain shower': require('../assets/heavyRain.png'),
    'Torrential rain shower': require('../assets/heavyRain.png'),
    'Light sleet showers': require('../assets/snow.png'),
    'Moderate or heavy sleet showers': require('../assets/snow.png'),
    'Light snow showers': require('../assets/snow.png'),
    'Moderate or heavy snow showers': require('../assets/snow.png'),
    'Light showers of ice pellets': require('../assets/snow.png'),
    'Moderate or heavy showers of ice pellets': require('../assets/snow.png'),
    'Patchy light rain with thunder': require('../assets/heavyRain.png'),
    'Moderate or heavy rain with thunder': require('../assets/heavyRain.png'),
    'Patchy light snow with thunder': require('../assets/snowwithThunder.png'),
    'Moderate or heavy snow with thunder': require('../assets/snowwithThunder.png')
  };
  